language: go
go:
  - 1.2
  - release
  - tip
install:
  - go get -d -t -v ./...
  - ./.travis/get_ci_vet.sh
  - ./.travis/get_ci_cover.sh
  - go get -v github.com/GeertJohan/fgt
  - go get -v github.com/golang/lint/golint
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - go vet
  - fgt golint .
  - go test -v
